[tools]
awscli   = "latest"
duckdb   = "latest"
go       = "latest"
jq       = "latest"
node     = "latest"
opentofu = "latest"
python   = "latest"
ruby     = "latest"
rust     = "latest"
usage    = "latest"

[settings]
ignored_config_paths                = ["~/.dotfiles"]
idiomatic_version_file_enable_tools = []
