#!/bin/bash
#
# Dotfiles
alias dot-dir="cd ~/.dotfiles"
alias dot-fetch="~/.dotfiles/bin/setup fetch"
alias dot-add="~/.dotfiles/bin/setup add"
alias dot-push="~/.dotfiles/bin/setup push"
alias dot-sync="~/.dotfiles/bin/setup sync"

# Homebrew
alias brewfile-update="~/.dotfiles/bin/setup brewfile"

# Vim
alias vi=vim
alias bim=vim

# Pass
alias pass-fetch="pass git pull"
alias pass-push="pass git push"

# Bundle
alias bi="bundle install --path ~/.bundle"

# Pass
alias pass-fetch="pass git pull"
alias pass-push="pass git push"
alias pass-sync="pass-fetch && pass-push"

# Vagrant
alias vup="vagrant up"
alias vd="vagrant destroy --force"
alias vp="vagrant provision"
alias vssh="vagrant ssh"

# Hugo Blog
alias blog-new="cd ~/surminus/hugo-blog && ./new.sh"
alias blog-update="cd ~/surminus/hugo-blog && ./deploy.sh"

# Git & Hub
alias gcmp="git compare"
alias gcm="git checkout master && git pull"
alias gpr="git push origin head && git pull-request"
alias gbr="git for-each-ref --format='%(committerdate) %09 %(authorname) %09 %(refname)' | sort -k5n -k2M -k3n -k4n"

# Misc
alias reload_shell="exec $SHELL && echo \"${SHELL} reloaded\""
alias shrug="echo '¯\_(ツ)_/¯'"

if which pt >/dev/null 2>&1 && which ack >/dev/null; then
  alias ack="pt"
fi

alias jenkins="fligo ssh -e build -u ubuntu -r deploy"

# Work VPN
alias vpn-on="nmcli con up uuid $(nmcli con |awk '/Work/ {print $2}')"
alias vpn-off="nmcli con down uuid $(nmcli con |awk '/Work/ {print $2}')"
