#!/bin/bash
#
# Dotfiles
alias dot-dir="cd ~/.dotfiles"
alias dot-fetch="~/.dotfiles/bin/setup fetch"
alias dot-add="~/.dotfiles/bin/setup add"
alias dot-push="~/.dotfiles/bin/setup push"
alias dot-sync="~/.dotfiles/bin/setup sync"

# Vim
alias vi=vim
alias bim=vim

# Pass
alias pass-fetch="pass git pull"
alias pass-push="pass git push"

# Bundle
alias bi="bundle install --path ~/.bundle"
alias be="bundle exec"

# Pass
alias pass-fetch="pass git pull"
alias pass-push="pass git push"
alias pass-sync="pass-fetch && pass-push"

# Vagrant
alias vup="vagrant up"
alias vd="vagrant destroy --force"
alias vp="vagrant provision"
alias vssh="vagrant ssh"

# Git
alias gco="git checkout"
alias gcm="git checkout master && git pull"
alias gpr="git push origin head && git pr"
